name: PR Merge Gform Data

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  update-on-merged-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install jq
        uses: vegardit/gha-setup-jq@v1

      - name: Run script to append Gform data to CSV file and remove Gform file
        if: startsWith(github.event.pull_request.title, 'gform_pr_')
        run: |
          chmod +x ./append-gform-data.sh
          ./append-gform-data.sh

      - name: Remove blank lines from CSV file
        run: |
          sed -i '/^$/d' ./rtbh.csv

      - name: Run script to regenerate Markdown table from CSV file
        run: |
          chmod +x ./csv_to_md.sh
          ./csv_to_md.sh

      - name: Run script to regenerate JSON file from CSV file
        run: |
          chmod +x ./csv_to_json.sh
          ./csv_to_json.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Merge gform data update from PR #${{ github.event.pull_request.number }} into CSV"
          git push origin main
